import {number,text,list,choice,clone} from '../core/numbers.mjs';
import {validateShape} from '../core/projects.mjs';
import park from '../../content/products/skamya-park.json' with {type:'json'};
export const methodologyVersion='1.0.0';
export const referenceVersions={catalogue:'1.0.0'};
export const snapshotTemplate={id:'',title:'',href:'',image:'',thumbnail:'',priceMode:'on_request',priceFrom:null,currency:'RUB',characteristics:'',materials:''};
export function snapshotProduct(p,href,thumbnail=''){return {id:p.slug,title:p.title,href,image:p.image||'',thumbnail,priceMode:p.priceMode,priceFrom:p.priceFrom??null,currency:p.currency||'RUB',characteristics:(p.dimensions||[]).filter(x=>x.isActive!==false).map(x=>`${x.label}: ${x.value}`).join('\n'),materials:(p.materials||[]).join(', ')};}
export const emptyRow={id:'',snapshot:clone(snapshotTemplate),quantity:1,zone:'',sizeWish:'',colorWish:'',executionWish:''};
export const example={variant:'Основной вариант',rows:[{...clone(emptyRow),id:'bench-demo',snapshot:snapshotProduct(park,'/ulichnaya-mebel/lavochki-i-skameyki/skamya-park/'),quantity:4,zone:'Входная группа',colorWish:'RAL 7016 (пожелание)'}],alternative:[]};
export const blank={variant:'Основной вариант',rows:[],alternative:[]};
export function validateDraft(input){validateShape(input,{variant:'',rows:[emptyRow],alternative:[emptyRow]});for(const r of [...input.rows,...input.alternative])validateSnapshot(r.snapshot);}
function safePath(value,label,allowBlank=false){const s=text(value,label,600);if(allowBlank&&!s)return s;if(!s.startsWith('/')||s.startsWith('//')||/[\\\r\n?#]/.test(s)||s.split('/').some(x=>x==='..')||/%(?:2e|2f|5c)/i.test(s))throw new Error(`${label}: ожидается путь опубликованного каталога.`);return s;}
export function validateSnapshot(s){validateShape(s,snapshotTemplate);text(s.id,'ID изделия',120);if(!/^[a-z0-9][a-z0-9-]*$/.test(s.id))throw new Error('Неверный ID изделия.');text(s.title,'Название изделия',250);safePath(s.href,'Ссылка изделия');safePath(s.image,'Фото',true);safePath(s.thumbnail,'Миниатюра',true);choice(s.priceMode,['on_request','from','fixed'],'Тип цены');if(s.priceFrom!==null)number(s.priceFrom,'Цена каталога',0,1e10);choice(s.currency,['RUB'],'Валюта');text(s.characteristics,'Характеристики',2000);text(s.materials,'Материалы',2000);}
export const signature=s=>JSON.stringify([s.id,s.title,s.href,s.image,s.priceMode,s.priceFrom,s.currency,s.characteristics,s.materials]);
export const configuration=r=>JSON.stringify([r.snapshot.id,r.zone.trim(),r.sizeWish.trim(),r.colorWish.trim(),r.executionWish.trim()]);
export function calculate(input,catalogue=[]){
  validateDraft(input);text(input.variant,'Вариант',120);
  function normalize(items){return list(items,'Ведомость',100).map((r,i)=>{validateSnapshot(r.snapshot);return {...clone(r),quantity:number(r.quantity,`Строка ${i+1}, количество`,1,10000,true),zone:text(r.zone,'Зона',160),sizeWish:text(r.sizeWish,'Размеры',400),colorWish:text(r.colorWish,'Цвет',400),executionWish:text(r.executionWish,'Исполнение',1000)};});}
  const items=normalize(input.rows),alternate=normalize(input.alternative);if(!items.length)throw new Error('Найдите изделие в каталоге и добавьте в ведомость.');
  const rows=items.map((r,i)=>{const live=catalogue.find(p=>p.id===r.snapshot.id);const status=!live?'Изделие сейчас отсутствует в опубликованном каталоге':signature(live)!==signature(r.snapshot)?'Данные каталога изменились; сохранён прежний снимок':'Снимок соответствует опубликованным данным';return {index:i+1,id:r.snapshot.id,name:r.snapshot.title,quantity:r.quantity,zone:r.zone||'Не указана',characteristics:r.snapshot.characteristics||'Числовые габариты не опубликованы',wishes:[r.sizeWish,r.colorWish,r.executionWish].filter(Boolean).join('; ')||'Не заданы',price:r.snapshot.priceMode==='on_request'||r.snapshot.priceFrom===null?'По запросу':`${r.snapshot.priceMode==='from'?'от ':''}${r.snapshot.priceFrom} ₽`,subtotal:r.snapshot.priceMode==='on_request'||r.snapshot.priceFrom===null?null:r.snapshot.priceFrom*r.quantity,priceMode:r.snapshot.priceMode,href:r.snapshot.href,status,snapshot:r.snapshot};});
  const priced=rows.filter(r=>r.subtotal!==null),knownCost=priced.reduce((n,r)=>n+r.subtotal,0),hasFrom=priced.some(r=>r.priceMode==='from');
  const quantities=items.reduce((n,r)=>n+r.quantity,0);
  const aggregate=items=>{const m=new Map();for(const r of items){const key=configuration(r);const old=m.get(key);m.set(key,{name:r.snapshot.title,zone:r.zone,wishes:[r.sizeWish,r.colorWish,r.executionWish].filter(Boolean).join('; '),quantity:(old?.quantity||0)+r.quantity});}return m;};
  const a=aggregate(items),b=aggregate(alternate),comparison=[...new Set([...a.keys(),...b.keys()])].map(k=>({name:(a.get(k)||b.get(k)).name,zone:(a.get(k)||b.get(k)).zone,wishes:(a.get(k)||b.get(k)).wishes,main:a.get(k)?.quantity||0,alternative:b.get(k)?.quantity||0,difference:(a.get(k)?.quantity||0)-(b.get(k)?.quantity||0)}));
  return {rows,items,comparison,knownCost,completeCost:priced.length===rows.length&&!hasFrom,summary:[{label:'Позиций',value:rows.length,unit:''},{label:'Изделий',value:quantities,unit:'шт.'},{label:priced.length!==rows.length?'Известная часть стоимости':hasFrom?'Стоимость по ценам «от»':'Стоимость по снимку каталога',value:priced.length?`${hasFrom?'от ':''}${knownCost.toLocaleString('ru-RU')}`:'По запросу',unit:priced.length?'₽':''}],columns:[{key:'index',label:'№'},{key:'id',label:'ID изделия'},{key:'name',label:'Изделие'},{key:'quantity',label:'Шт.'},{key:'zone',label:'Зона'},{key:'characteristics',label:'Опубликованные характеристики'},{key:'wishes',label:'Пожелания заказчика'},{key:'price',label:'Цена за шт.'},{key:'href',label:'Ссылка'},{key:'status',label:'Состояние снимка'}],warnings:['Размеры, цвета и исполнение в полях пожеланий требуют согласования. Они не являются подтверждёнными характеристиками товара.','Ведомость не подтверждает наличие, совместимость и итоговую стоимость. Изготовление и комплектация уточняются по запросу.',...(priced.length!==rows.length?['Полный итог стоимости неизвестен: у части изделий цена по запросу.']:[]),...(hasFrom?['Цены «от» — начальные. Изменение исполнения может изменить стоимость.']:[])],extraTables:alternate.length?[{title:'Сравнение комплектаций (основной − альтернативный)',columns:[{key:'name',label:'Изделие'},{key:'zone',label:'Зона'},{key:'wishes',label:'Исполнение'},{key:'main',label:'Основной, шт.'},{key:'alternative',label:'Альтернативный, шт.'},{key:'difference',label:'Разница, шт.'}],rows:comparison}]:[]};
}
export function addItem(input,snapshot){validateSnapshot(snapshot);const row={...clone(emptyRow),id:`item-${Date.now()}-${Math.random().toString(36).slice(2)}`,snapshot:clone(snapshot)};const same=input.rows.find(r=>configuration(r)===configuration(row)&&signature(r.snapshot)===signature(snapshot));if(same)same.quantity=number(same.quantity,'Количество',1,9999,true)+1;else {if(input.rows.length>=100)throw new Error('Не более 100 строк.');input.rows.push(row);}return input;}
